# Generated by Django 3.2.9 on 2021-11-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='tempo_de_preparo',
            new_name='tempo_preparo',
        ),
    ]
